### ISSUE TITLE
.MOD files support

### ISSUE THREAD

**Issue by EduApps-CDG** [marcrobledo/RomPatcher.js#11]
I cant patch my N64 game

**Comment by marcrobledo** [comment]
I can't find any information about its file structure nor even just a .mod patch file 😄 
Can you provide any of them?

**Comment by marcrobledo** [comment]
I have been doing some research. Looks like it's an exclusive format for Paper Mario (N64) Star Rod editor.
Official page and download are already dead, couldn't find the original sourcecode nor information about the file structure.

Fortunately, after some reverse engineering I managed to crack the format, it's quite simple and very similar to IPS. Support will be available soon.

**Comment by EduApps-CDG** [comment]
I have the file

**Comment by EduApps-CDG** [comment]
See [here](https://drive.google.com/file/d/1Vvhml-n2LHq17tczwRgHdFkSAvZOu9FN/view?usp=drivesdk)

**Comment by EduApps-CDG** [comment]
> it's quite simple and very similar to IPS.
Well, thanks

**Comment by marcrobledo** [comment]
Basic support for .mod files have been added.
Let me know if it works for you.

Also, make sure the cached webapp gets updated and you are using version 2.2

**Comment by EduApps-CDG** [comment]
I will try

**Comment by EduApps-CDG** [comment]
![Screenshot_20200309-024654](https://user-images.githubusercontent.com/32627482/76186241-78f9da00-61b0-11ea-8c10-7533e1d506dc.png)
Just a black screen.

Version: 2.2b

**Comment by marcrobledo** [comment]
Which patch did you use?
Can you test the ROM in another emulator?

**Comment by marcrobledo** [comment]
I've tried that Book of Mario.mod file you posted and it runs fine with Mupen64.

Are you sure you used the needed Paper Mario (USA).z64 ROM (CRC32: A7F5CD7E
) as a base?

**Comment by EduApps-CDG** [comment]
# #
Here is the info:
![Screenshot_20200310-103654~2](https://user-images.githubusercontent.com/32627482/76317708-5d2f2a80-62bb-11ea-9087-5c3a5fc613e2.png)
as you can see is a `.N64` file and is not the same CRC32, but same game.

**Comment by marcrobledo** [comment]
Paper Mario Star Rod .mod format works only with a valid Paper Mario (USA).z64 ROM. Do not use .n64 format.

**Comment by EduApps-CDG** [comment]
Okay, thanks
