### ISSUE TITLE
Can’t select IPS file in iPhone

### ISSUE THREAD

**Issue by jamescastells** [marcrobledo/RomPatcher.js#12]
On an iPhone, I access the page and if I click the “patch file” button I can browse the files in my Files app but the IPS file is not selectable. I can however select the ROM by clicking in “ROM file”.

**Comment by marcrobledo** [comment]
I do not own an iPhone, so I cannot test it there :-(

I'll leave the issue open, just in case someone can help.

**Comment by iMonZ** [comment]
I have an iPhone but the problem is,

That you need to enable only for safari that you could select every file extension type!
This would fix this problem!
Because you can currently only select .zip files at the patch region
(The Rom region works without a problem)

**Comment by iMonZ** [comment]
Edit:
This is not an iPhone problem This is only an Safari problem with other browsers everything works as expected

**Comment by marcrobledo** [comment]
Is this happening with current and most up to date Safari versions? Or is it happening with old versions?

According to these: (https://stackoverflow.com/questions/19107685/safari-input-type-file-accept-video-ignores-mp4-files)[1], (https://stackoverflow.com/questions/47386981/input-type-file-attribute-accept-not-working-in-safari-on-macbook)[2] and (https://caniuse.com/#feat=input-file-accept)[3], the `input type="file" accept=""` accept attribute. But answers and solutions are quite outdated.

I could fix it by adding a dirty patch for Safari, but I'd need to confirm this is also happening in most recent versions.

**Comment by asc6** [comment]
I know it's still a beta but I ran into this issue on iPadOS 14 today. It seems to be the exact same problem. I can upload a zip file from the file explorer but I can't upload bps files. Works fine from macOS Catalina (don't have Big Sur installed) in Safari so it seems to be just a mobile Safari bug.  I will file a bug report with Apple on mobile safari ignoring parts of the accept attribute and hopefully they can fix it.

**Comment by marcrobledo** [comment]
So looks like it's just a Safari Mobile issue.


Commit a4eb4b1 adds a dirty fix for it (what it does is just simply removing the `accept=""` attribute when loading page. I haven't tested it with Safari Mobile (I don't own any iOS device), but it should work.

Let me know if it fixes it. Make sure you are using RomPatcher.js 2.3**b**.

**Comment by seajaysec** [comment]
Hey just wanted to share that this is still broken on mobile safari on iOS 15.

**Comment by planet0** [comment]
I also wanted to share that I can't seem to get it working with Safari on macOS Monterey.

**Comment by iMonZ** [comment]
Works for me issue can be closed now.

**Comment by seajaysec** [comment]
@iMonZ - The issue remains, on mobile Safari at least, and shouldn't be closed.

**Comment by marcrobledo** [comment]
Is this still happening?

**Comment by seajaysec** [comment]
> Is this still happening?

No! Just tested and it's working great now. Thank you!!

**Comment by marcrobledo** [comment]
> No! Just tested and it's working great now. Thank you!!
Glad to hear that! :-)

> @marcrobledo maybe you can add the desktop safari user agent either because currently you only mention Mobile Safari.
If I do that, then real desktop Safari users would also be affected and wouldn't be benefited from the `accept` attribute. According to [caniuse](https://caniuse.com/input-file-accept), the desktop Safari does support it correctly.
I figure setting Desktop user agent in mobile Safari does not keep the iPhone/iPad string in it (correct me if I'm wrong!), so it would be impossible to distinguish faked useragent from real desktop browsers.
