### ISSUE TITLE
Permission to use this on my website?

### ISSUE THREAD

**Issue by ZPaul2Fresh8** [marcrobledo/RomPatcher.js#13]
I wanted to ask if I could use this on a website of mine that is related to hacking arcade games? I provide new revisions of older Midway games and the method for distribution is patches to the original ROMs. Some more info on setup would be much appreciated if you have the time as well. Thank you for your time Marco.

-Paul

**Comment by marcrobledo** [comment]
Sure, it's free to use :-)

You should be able to install it in your server just by downloading the whole package [here](https://github.com/marcrobledo/RomPatcher.js/releases/tag/2.3) (Source code .zip). Then just upload all files (keeping the directory structure) it to your server.

There is a way to make it a standalone customized patcher, so it just downloads automatically the patches from your server, user will only need to provide the ROM file.

It's not documented, unfortunately. Take a look at the index.html and look for this commented block: PREDEFINED PATCHES EXAMPLE
Uncomment it, and edit it to your needs. Let me know if you need more help.


PD: My name is Marc, without the o :-D

**Comment by ZPaul2Fresh8** [comment]
Ahh my apologies for the name error! Thank you so much for your help. When
I get some time I'll see if I can implement into the mortalkombatplus.com
website I have.

Thanks once again and have a great day!

-Paul
