### ISSUE TITLE
Any zelda rom i try the end results are the same

### ISSUE THREAD

**Issue by gatekeeper1122** [marcrobledo/RomPatcher.js#14]
whats with this tool? lots of ppl reccemend it to be useful & works 100% for them yet when i try to use it to patch zelda ocarina of time with any patch i get this error instantly i could have used every single one i could find for the game even if i dump it with the real game card id still get the same results are the roms at fault or the patches im trying to use?
![image](https://user-images.githubusercontent.com/16184353/86260907-24250980-bb7b-11ea-92b8-2bf077ae4eec.png)

**Comment by HeuristicPerson** [comment]
Can you please post the CRC32/MD5/SHA-1 of the ROM(s) and a link to the patch? I want to give it a go...

Regards

**Comment by gatekeeper1122** [comment]
> Can you please post the CRC32/MD5/SHA-1 of the ROM(s) and a link to the patch? I want to give it a go...
> 
> Regards

you got discord? add me gatekeeper#9846

**Comment by HeuristicPerson** [comment]
I tried but "Hm, didn't work. Double check taht the capitalization, spelling, any spaces, and numbers are correct."

**Comment by gatekeeper1122** [comment]
oops i forgot the numbers my bad gatekeeper1122#9846

**Comment by marcrobledo** [comment]
Post a link to the patch.

N64 ROMs can be in two formats (little and big endian). You must use the correct ROM format that the patch requires.
There are tools out there that allows you to convert from/to big/little endian easily.
