### ISSUE TITLE
Unable to Patch .nds file using .xdelta?

### ISSUE THREAD

**Issue by BrianSantoso** [marcrobledo/RomPatcher.js#22]
Following error occured when trying to patch .nds ROM using .xdelta patch
![image](https://user-images.githubusercontent.com/22692190/103432455-ef2e5980-4b93-11eb-811b-916feec778e0.png)

CRC32:
ffd28f00
MD5:
ae2a483d0a5e8130d39f44f41a86df57
SHA-1:
30793e274fb4c7ba070ae226edbdfe355504b1f5

**Comment by Drakonas** [comment]
Just wanted to note that this is a confirmed clean dump based on the CRC.

**Comment by marcrobledo** [comment]
Clone of #5

xdelta secondary decompressor is not supported.
