### ISSUE TITLE
Creating patches -- Offset is out of range

### ISSUE THREAD

**Issue by snarfblam** [marcrobledo/RomPatcher.js#3]
I'm actually encountering errors when trying to create patches, using Chrome 65.0.3325.181. Worth pointing out that the errors aren't handled so it fails silently and the UI simply appears to be unresponsive.

This is the most common and occurred in multiple scenarios (different ROMs, trying to create both IPS and UPS). For example, trying to create a patch from "Metroid (U).nes" to MDbTroid, both IPS and UPS:
```
RomPatcher.js:239 Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at MarcBinFile.readByte (RomPatcher.js:239)
    at createIPSFromFiles (ips.js:154)
    at createPatchFile (RomPatcher.js:132)
    at HTMLButtonElement.onclick ((index):103)
```
This comes up if the source and modified ROM are the same.
```
ips.js:72 Uncaught TypeError: Cannot read property 'truncate' of undefined
    at IPS.export (ips.js:72)
    at createPatchFile (RomPatcher.js:144)
    at HTMLButtonElement.onclick ((index):103)
  | IPS.export | @ | ips.js:72
  | createPatchFile | @ | RomPatcher.js:144
  | onclick | @ | (index):103
```

**Comment by marcrobledo** [comment]
Thank you for reporting.
Should be fixed in eb40a592b52918992dc09b930663af4235e22691
:-D
