### ISSUE TITLE
feature request: name output file to patch name, not input name (patched)

### ISSUE THREAD

**Issue by foxsouns** [marcrobledo/RomPatcher.js#31]
with most files, esp smw romhacks, it makes more sense to name it the name of the patch than to name it a generic smw patched thing. i might dive through the source code myself and find what makes the name, but i am garbage at js and would rather leave it to someone who knows what theyre doing.

**Comment by marcrobledo** [comment]
I've been going over adding a settings screen that would allow, among other things, choosing the output filename with both options.
What do you think?

**Comment by foxsouns** [comment]
that sounds great!

**Comment by marcrobledo** [comment]
I managed to get some time to finish this at last! Hoping to release it soon :-)

**Comment by marcrobledo** [comment]
Any suggestion for a better setting label?
![imagen](https://user-images.githubusercontent.com/14358263/159682877-23960e78-c57b-40ac-88af-d506a04d9c08.png)

**Comment by laqieer** [comment]
> Any suggestion for a shorter setting label?

Output filename:
- ROM filename
- Patch filename

**Comment by marcrobledo** [comment]
Yeah, I already thought on those.
But I'd rather prefer it to be a simple checkbox, not a dropdown (if possible).

**Comment by foxsouns** [comment]
> Yeah, I already thought on those. But I'd rather prefer it to be a simple checkbox, not a dropdown (if possible).

`Use patch name for output`
?

**Comment by marcrobledo** [comment]
I've just deployed the new 2.6 version! Let me know what you think about it :-)

**Comment by GB-CG** [comment]
Your patcher over at [RHDN](https://www.romhacking.net/patch/) is still using 2.5.1.

**Comment by marcrobledo** [comment]
Yes. I prefer to test it here before uploading it there.

**Comment by foxsouns** [comment]
@marcrobledo im not sure what is going on, but the site is not working on chromium.

![Screenshot 1](https://user-images.githubusercontent.com/60267141/160021667-6eb00068-e9da-45c2-bfa4-f78b2801bbec.png)
![Screenshot 2](https://user-images.githubusercontent.com/60267141/160021668-0bd2edb7-dacf-40f7-be31-838d8788ebde.png)

**Comment by marcrobledo** [comment]
> @marcrobledo im not sure what is going on, but the site is not working on chromium.

Looks like it hasn't  loaded the CSS stylesheet for some reason. Can you try to force a cache refresh?

**Comment by foxsouns** [comment]
> > @marcrobledo im not sure what is going on, but the site is not working on chromium.
> 
> Looks like it hasn't loaded the CSS stylesheet for some reason. Can you try to force a cache refresh?

it is working now, after a refresh.
