### ISSUE TITLE
.DIFF / .PATCH support?

### ISSUE THREAD

**Issue by NintendoManiac64** [marcrobledo/RomPatcher.js#32]
Apparently the ".DIFF" / ".PATCH" format has been the go-to solution for like 50 years in terms of source code patching rather than binary patching.  I don't suppose it'd be too difficult to add it then?

Basically there's an [open-source piece of software that people have created patch fixes for in .DIFF format](https://github.com/EbonJaeger/nosquint/issues/16#issuecomment-971763886), but me and my lack of code savvy-ness is making things a bit difficult to get this working which made me wonder why an easy-to-use patcher doesn't exist for the format if it's as prevalent as it sounds (my guess is that it's kind of a "for coders by coders" and so nobody ever ran into the situation of a non-coding-savvy user needing to run such a file)

**Comment by foxsouns** [comment]
@NintendoManiac64 .diff files basically define changes to be made from the source repo, in a way very similar to the rom patch files this tool is known for implementing, however .diff is not for roms, so i dont think it would make sense to include it. 

however, if you were trying to do this on the link you gave, and are stuck on browser, i would personally try to use replit for this. 

make a replit thing, clone the repo with `git clone https://github.com/EbonJaeger/nosquint.git`, download the diff file to replit and unzip it using `wget https://github.com/EbonJaeger/nosquint/files/7556382/nosquint_nofuel.zip && unzip nosquint_nofuel.zip`, and then run `cd nosquint && git am ../whatever_the_path_to_the_thing_is.diff && ./build-xpi.sh`, obviously changing the part after `../` to the file name.

**Comment by NintendoManiac64** [comment]
> however .diff is not for roms, so i dont think it would make sense to include it.

I know of people that have used BPS and xDelta as a way to update and/or mod native PC games and such rather than for roms since they work with any sort of singular file whether it be a rom, an archive, an image, etc.

I say this because, AFAICT, the .DIFF file is patching a singular .JAR file, and therefore I don't really see how that's any different from how ROM patch files patch a singular file.

**Comment by foxsouns** [comment]
i see. well then, i am trash at js, so let's hope someone who isnt will pick this up.

**Comment by EbonJaeger** [comment]
> I say this because, AFAICT, the .DIFF file is patching a singular .JAR file

I'm only chiming in here to try to prevent further confusion.

`.diff` (or also commonly `.patch`) files simply patch a (non-compiled) source code file in a Git repository. As far as I can tell, this repo is for patching binary archives or ROMs (compiled code and assets), which is significantly different and only tangentially related at best.

**Comment by NintendoManiac64** [comment]
> In this particular case, one is operating at the source level (.diff with NoSquint), and the other at the compiled level (ROM).

Perhaps it's my general lack of understanding of coding stuff, but from my perspective as a user the input and output is not any different - a singular patch file is applied to a singular pre-existing file to transform it into a different singular file.

I mean, I actually just recently used xDelta patches as a way to supply a fix for a hour-long MP4 video file of all things where its audio and video would go out of sync.

**Comment by foxsouns** [comment]
@NintendoManiac64: coming back and necroposting here to say that diff/patch isnt xdelta; diff/patch works by changing textual stuff, and everything supported here changes binary stuff. they dont work the same and are used for different purposes. as said above: use a diff tool for these files, and replit will work if you desperately need a web-browser solution for this.
