### ISSUE TITLE
Using setMessage Doesn't Set A data-localize Attribute

### ISSUE THREAD

**Issue by flagrama** [marcrobledo/RomPatcher.js#36]
When using `setMessage` it doesn't set a `data-localize` attribute on the element the message is added to. Due to this if you change the language after `setMessage` has set a message it will still appear in the previously selected language.

I think ideally instead of `msg` you take in the localization key instead, then set `data-localize` to that key and set the message by passing the key to `_` inside of `setMessage`.

I can write up a quick PR if this implementation sounds good to you.

**Comment by marcrobledo** [comment]
Sure!
