### ISSUE TITLE
Problem with parasite eve 1

### ISSUE THREAD

**Issue by Felipefpl** [marcrobledo/RomPatcher.js#39]
I used the online patcher to apply this hack https://www.romhacking.net/hacks/1950/ and the browser crashed when i was patching the CD 2 of the game.

The patch works using ppf-o-matic 3.0

**Comment by marcrobledo** [comment]
It is working fine on my side.
Are you using the correct track file `crc32: 226EE2EE`?

**Comment by Felipefpl** [comment]
Yes, i used a tool to check it.

**Comment by marcrobledo** [comment]
Which browser and version are you using?
If the entire browser crashed, it might probably be a memory overflow.

**Comment by Felipefpl** [comment]
I'm using waterfox, i'm also wondering if those errors could have something to do with it https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.romhacking.net%2Fpatch%2F

**Comment by marcrobledo** [comment]
It would help to know what error message appeared.
Have you tried it again after a browser fresh reboot?

**Comment by Felipefpl** [comment]
Error msg: "There is no sufficient memory to complete the action you requested.

Quit some applications and try again."

This msg didnt show up when i patched the 1st CD.

After a fresh reboot the tab crashed.

**Comment by marcrobledo** [comment]
Which version of waterfox are you using?
Maybe is it too old and/or ServiceWorkers are disabled for some reason?

**Comment by Felipefpl** [comment]
i always use the latest version of waterfox and serviceworkers is disabled, why serviceworkers are needed?

**Comment by marcrobledo** [comment]
Sorry, I meant Web Workers (not Service Workers, which are a completetly different thing).

Web Workers allow browsers to run JavaScript code in the background and in a different thread than the browser's renderization engine. Patching ROMs can become a heavy task in some cases (specially with big ISOs like this one), and a dedicated Web Worker facilitates the task.

If ServiceWorkers are not enabled, Rom Patcher JS will try to patch using the old method, which is much more slow and consumes a lot of memory if patching a very big file like a PSX iso.


Please, let me know if you've got Web Workers enabled.

**Comment by Felipefpl** [comment]
I see, that's a good info to know. Could you please tell me the name of the function that i need to search in the about:config? There are several "workers" functions there and i dont know which one you are talking about.

**Comment by marcrobledo** [comment]
I don't know :-(

Web Workers should be enabled by default in all modern browsers.

Another way to check if Rom Patcher JS is using Web Workers is to check the value for `CAN_USE_WEB_WORKERS` variable. Just open Rom Patcher JS in a new tab and press F12 to open Web Development Console, then type `CAN_USE_WEB_WORKERS` and it will return true or false.

**Comment by marcrobledo** [comment]
Are you using an old computer with little memory?

**Comment by Felipefpl** [comment]
I have a 1.8 Ghz sandy-bridge with 4 GB RAM  and win7 x64. I dont think it's a problem, like i said, the patching of cd 1 works fine.

**Comment by marcrobledo** [comment]
4GB will probably be enough for the standalone PPF-o-matic, but there a lot of factors that could make it insufficient when running high-level code like JS under a web browser, which wasn't built specifically for binary data management.

Patching CD1 works probably because the patch isn't as complex and maybe doesn't relocat as much data as CD2.

I'm sorry but there isn't much I can do on this :-(

**Comment by Felipefpl** [comment]
Ok, thanks for the answers.
