### ISSUE TITLE
JAR files are being treated as ZIP files.

### ISSUE THREAD

**Issue by anonymous5555522222** [marcrobledo/RomPatcher.js#53]
Because of this, it's impossible to patch J2ME video-games.

**Comment by marcrobledo** [comment]
Fixed in 0769fae972b04ed594b0fc11bdddbbf6d6037543

**Comment by anonymous5555522222** [comment]
> Fixed in [0769fae](https://github.com/marcrobledo/RomPatcher.js/commit/0769fae972b04ed594b0fc11bdddbbf6d6037543)

Thank you.
