### ISSUE TITLE
Cant apply .aps patches

### ISSUE THREAD

**Issue by AzazelHD** [marcrobledo/RomPatcher.js#58]
Im trying to apply Final fantasy tactics advance X patch, but it doesnt allow me

**Comment by marcrobledo** [comment]
Can you provide me a link with the patch so I can try it out?

**Comment by AzazelHD** [comment]
Hi, sure. I got it from here
http://ngplus.net/InsaneDifficultyArchive/www.insanedifficulty.com/board/index9837.html?/files/file/65-final-fantasy-tactics-advance-x/

**Comment by marcrobledo** [comment]
Thank you for your feedback, should be fixed in 1ea536a!

**Comment by AzazelHD** [comment]
Thanks you too for fixing it ^^ Tyvm, rlly
