### ISSUE TITLE
Error using a BPS patch

### ISSUE THREAD

**Issue by ze10** [marcrobledo/RomPatcher.js#6]
I tried to use the English translation patch (a BPS file) for Super Famicom Wars rom using the patcher, but I got this error. Am I doing anything wrong?

Uncaught RangeError: Offset is outside the bounds of the DataView 
    at DataView.getUint8 (\<anonymous>)
    at MarcBinFile.readByte (RomPatcher.js:291)
    at BPS.apply (bps.js:82)
    at applyPatchFile (RomPatcher.js:140)
    at HTMLButtonElement.onclick ((index):65)

**Comment by marcrobledo** [comment]
That error was fixed some weeks ago.

Make sure you are using rev20180920 or later (read the footer). Use Ctrl+F5 to force it to load the latest version.
Your web browser might be probably loading an old cached version and isn't downloading the latest one for some reason, which also happened to me in Firefox (and I'm going to take a look asap!).

Are you using Firefox?
