### ISSUE TITLE
[FR] show source checksum from input patch

### ISSUE THREAD

**Issue by eadmaster** [marcrobledo/RomPatcher.js#69]
Some patch formats provide a source checksum in the header (e.g. [BPS](https://github.com/blakesmith/rombp/blob/master/docs/bps_spec.md))

This could save some time finding the right input rom, in case the hash is missing from the readme.

example python script to read the hash from a bps patch
````
def read_bps_header(filename):
    # https://github.com/blakesmith/rombp/blob/master/docs/bps_spec.md
    with open(filename, 'rb') as f:
        magic = f.read(4)
        if magic != b'BPS1':
            raise ValueError("Not a BPS patch")
        
        # Read source and target hashes
        source_crc32 = struct.unpack('<I', f.read(4))[0]
        target_crc32 = struct.unpack('<I', f.read(4))[0]
        
        print(f"Source CRC32: {source_crc32:08X}")
        print(f"Target CRC32: {target_crc32:08X}")
````

EDIT: other formats that should include the source checksum within the patch file itself (still unverified by me):

 - [UPS](https://www.romhacking.net/documents/392/)
 - [xdelta (optional?)](https://github.com/jmacd/xdelta)

**Comment by marcrobledo** [comment]
Should be implemented now in commit c1293bb3ed6a206d799e18fafc5583939bb37d5a !
