### ISSUE TITLE
BUG: You Can't Combine Roms?

### ISSUE THREAD

**Issue by Pfoxj** [marcrobledo/RomPatcher.js#72]
Ok, I Make a Genesis Patch For Sonic 3 And Knuckles By Combining Sonic 3 And Sonic And Knuckles In The "Create Patch" Section, Then I Apply It To a Rom, But It Gives Me An Error: "No ROM/patch selected" WHAT!?! Like, This Has To Be Fixed.
![Screenshot Of Error](https://github.com/marcrobledo/RomPatcher.js/assets/167392704/d90f8099-f69a-4193-af60-73567237185b)

**Comment by marcrobledo** [comment]
What website are you visiting? That's an old version for sure.
Make sure you are visiting the latest official version here: https://www.marcrobledo.com/RomPatcher.js/

**Comment by Pfoxj** [comment]
> What website are you visiting? That's an old version for sure. Make sure you are visiting the latest official version here: https://www.marcrobledo.com/RomPatcher.js/

_gasp_ I hate that version, it looks bad, and has features removed, plus, it worked, but didn't play on my emulator!
![Emulator Screenshot](https://github.com/marcrobledo/RomPatcher.js/assets/167392704/6543a367-8f4c-434b-9682-2b370f1a0368)

**Comment by marcrobledo** [comment]
It has no features removed.

**Comment by marcrobledo** [comment]
But anyway, if I understood correctly, you have tried to create a patch with two totally different ROMs. So you created a patch that turns Sonic 3 into S&K, it doesn't combine them.

**Comment by Pfoxj** [comment]
> But anyway, if I understood correctly, you have tried to create a patch with two totally different ROMs. So you created a patch that turns Sonic 3 into S&K, it doesn't combine them. You cannot combine those games by creating a patch.

But How Do I Combine Them To Make Sonic 3 And Knuckles? Give Me An Online Tool To Do It.
