### ISSUE TITLE
Generated BPS patches have a checksum mismatch in latest version.

### ISSUE THREAD

**Issue by dewgong64** [marcrobledo/RomPatcher.js#75]
After the most recent release (version 3), I've noticed that some BPS patches are broken. The only difference between the working patch (one I generated months ago) and the broken one, is that the last four bytes of each patch files are different. Additionally, if the broken patch file is selected (even if no base rom is present), the site will get stuck.

I've attached the original file, modified file, valid patch, and invalid patch files that have this issue.
[example_files.zip](https://github.com/user-attachments/files/16685599/example_files.zip)

**Comment by marcrobledo** [comment]
Should be fixed in 4a928085fc4893e8d6af446dd085d5afdc745c08 (v3.0 RC3).

Thank you!

**Comment by marcrobledo** [comment]
Feel free to close the issue whenever you confirm it's working.

**Comment by dewgong64** [comment]
> Feel free to close the issue whenever you confirm it's working.

Yeah, everything seems good. Thanks for fixing this so quickly!
