### ISSUE TITLE
Request: Passing ROM file programmatically

### ISSUE THREAD

**Issue by Stewmath** [marcrobledo/RomPatcher.js#77]
I've been looking into setting this up for making it easier to apply patches from here: https://wiki.zeldahacking.net/oracle/List_of_hacks

All of these patches are applied to one of two games, Oracle of Ages or Oracle of Seasons. I thought it would be nice if, after being selected once, the ROM could be stored in local storage and passed directly to RomPatcher.js instead of having to select the file again each time the page is reloaded.

Depending on a file dialog makes it impossible to automate this since it can't be interacted with programmatically, for obvious security reasons.

**Comment by marcrobledo** [comment]
Unfortunately, localStorage can only store strings and it has a limit of 5 megabytes per domain.
I figure [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) would a better solution.

Still, this is a very specific issue. The embeded patcher in this repo is just a basic web implementation of Rom Patcher JS. Not sure if I should add a feature like that, the main aim was to provide an easy to embed patcher.
You could expand the capabilities of the current web implementation by editing `RomPatcher.webapp.js`, so it saves the ROM data in IndexedDB when user provides the file (not sure what would be the performance impact though).


Anyway, I'm going to add your site to the list of sites that use Rom Patcher JS :-) Thank you for using it.

**Comment by Stewmath** [comment]
Yeah I figured this is a bit too specific to my use-case but I thought I'd throw it out there anyway. Thanks for making this!
