### ISSUE TITLE
UI is disabled after cancelling ROM file chooser

### ISSUE THREAD

**Issue by xenophile127** [marcrobledo/RomPatcher.js#79]
**Reproduction Steps**:
1. Choose a ROM file.
2. Click to open the file chooser a second time (like you're choosing a different ROM file).
3. Close the file chooser without selecting anything.

**Expected Results**: File chooser can be opened a third time.

**Actual Results**: UI is disabled.

<img width="600" alt="Screenshot 2024-09-03 at 10 19 28" src="https://github.com/user-attachments/assets/b6a23622-5911-4faa-aa02-bb97ddc65bf6">

**Comment by marcrobledo** [comment]
Nevermind, I can reproduce it in Chrome W10.

**Comment by marcrobledo** [comment]
Should be fixed now in RC5.

**Comment by xenophile127** [comment]
Verified in RC5. File selection is now sticky after a cancel.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
