### ISSUE TITLE
Some iOS devices don't allow chosing patch files

### ISSUE THREAD

**Issue by marcrobledo** [marcrobledo/RomPatcher.js#80]
Apparently, some iOS users cannot select a patch file. They see the files in the file browser but they are greyed out.
If they revert to Legacy 2.9.1 version, it works perfectly.

I can't give much description to this issue, as a few users reported it to me as Twitter DMs and they didn't gave much details :-/

I am not an iOS user, so I cannot test it. Can anyone help with this and provide more information and/or feedback?
I can pay a BrowserStack subscription to try to fix it, but it's limited to 100 minutes of usage per month. So I prefer to get more info beforehand.

**Comment by se09deluca** [comment]
I'm experiencing this issue too.
If can help, I can tell that the form in 'creator mode' has the .ups files selectable.

I'm running iOS 18 beta 8.

**Comment by marcrobledo** [comment]
> I'm experiencing this issue too. If can help, I can tell that the form in 'creator mode' has the .ups files selectable.
> 
> I'm running iOS 18 beta 8.

Can you give more details? Device, browser and version, steps to reproduce it...

**Comment by se09deluca** [comment]
> > I'm experiencing this issue too. If can help, I can tell that the form in 'creator mode' has the .ups files selectable.
> 
> > 
> 
> > I'm running iOS 18 beta 8.
> 
> 
> 
> Can you give more details? Device, browser and version, steps to reproduce it...

Device:
iPhone 12 Pro
Os: iOS 18 beta 8
Browser: 
Chrome 128.0.6613.98
But same behaviour with Safari 
Steps:
After page load, press on base rom input and select the base rom, after that press on the patch input and the file picker opens but the items are not selectable (typical behaviour of non accepted mimetypes).

**Comment by xenophile127** [comment]
@se09deluca, I tried reproducing and was not able to. I used iPad OS 15.8.2 with Safari.

Attempted Reproduction Steps:
1. Copy ffa.gb with MD5 of 24cd3bdf490ef2e1aa6a8af380eccd78 to iPad via AirDrop and save to Files.
2. Visit https://xenophile127.github.io/Legend-of-the-Mana-Sword/patch.html
3. Touch ROM file input and select ffa.gb
4. Touch Patch input and switch from LotMS (Amanda) to LotMS (Duke)
5. Touch Patch input and switch from LotMS (Duke) to LotMS (Amanda)
6. Press Apply patch button and confirm downloading.

Where did I go right?

**Comment by marcrobledo** [comment]
> @se09deluca, I tried reproducing and was not able to. I used iPad OS 15.8.2 with Safari.
> 
> Attempted Reproduction Steps:
> 
>     1. Copy ffa.gb with MD5 of 24cd3bdf490ef2e1aa6a8af380eccd78 to iPad via AirDrop and save to Files.
> 
>     2. Visit https://xenophile127.github.io/Legend-of-the-Mana-Sword/patch.html
> 
>     3. Touch ROM file input and select ffa.gb
> 
>     4. Touch Patch input and switch from LotMS (Amanda) to LotMS (Duke)
> 
>     5. Touch Patch input and switch from LotMS (Duke) to LotMS (Amanda)
> 
>     6. Press Apply patch button and confirm downloading.
> 
> 
> Where did I go right?

The bug cannot be reproduced with embeded patches, as there is no file browser for patches!

**Comment by xenophile127** [comment]
**Reproduction Steps**:
1. Download an ips file to your iOS device.
2. Download a zip file to your iOS device.
3. Visit https://www.marcrobledo.com/RomPatcher.js/
4. Touch Patch file input.

**Expected Results**:
Both the ips file and the zip file are selectable.

**Actual Results**:
Only the zip file is selectable.

**Note**:
The behavior of bps files is identical to ips.

**Debugging**:
I found reference online at https://caniuse.com/input-file-accept that Safari on iOS "Supports the type format (e.g. image/*) but not the extension format (e.g. .png)".

I used https://www.htmlstrip.com/mime-file-type-checker to test the mime-type of an ips file and a bps file and both were "application/octet-stream". Adding that mime-type to the file input's accept list allowed for ips and bps files to be selected.

There is also some information online about using an onchange handler as a workaround.

**Comment by marcrobledo** [comment]
I am aware of that odd Safari behaviour. Indeed, this was fixed many years ago.

When rewritting 3.0, I supposed Safari had already changed the way the file browser works and that's why I removed [the workaround](https://github.com/marcrobledo/RomPatcher.js/blob/a0105768392ad20baa71c336b322904fa3d1c157/legacy/js/RomPatcher.js#L330). Looks like I was wrong.
I'll be reverting this, thank you.

However, not sure if it is a thing with Safari, as @se09deluca mentioned that it also happens in Chrome.

**Comment by se09deluca** [comment]
> I am aware of that odd Safari behaviour. Indeed, this was fixed many years ago.
> 
> When rewritting 3.0, I supposed Safari had already changed the way the file browser works and that's why I removed [the workaround](https://github.com/marcrobledo/RomPatcher.js/blob/a0105768392ad20baa71c336b322904fa3d1c157/legacy/js/RomPatcher.js#L330). Looks like I was wrong. I'll be reverting this, thank you.
> 
> However, not sure if it is a thing with Safari, as @se09deluca mentioned that it also happens in Chrome.

Yes, i confirm that happens also in Chrome. 
Maybe [Google Chrome still uses Apple Webkit](https://en.wikipedia.org/wiki/WebKit#cite_note-App_Store_Review_Guidelines-48:~:text=Chrome%20for%20iOS%20continues%20to%20use%20WebKit%20because%20Apple%20requires%20that%20web%20browsers%20on%20that%20platform%20must%20do%20so.), since apple [opened iOS to non webkit-based  browser engines](https://developer.apple.com/support/alternative-browser-engines/) only with [iOS 17.4](https://en.wikipedia.org/wiki/IOS_17#Release_history:~:text=Release%20notes-,17.4,-21E219)

**Comment by marcrobledo** [comment]
Should be fixed now in RC5.
@se09deluca can you test it in iOS Chrome as well?

**Comment by se09deluca** [comment]
> Should be fixed now in RC5.
> 
> @se09deluca can you test it in iOS Chrome as well?

Now it works as expected.

**Comment by xenophile127** [comment]
> Should be fixed now in RC5.

Fixed for me in Safari.

**Comment by marcrobledo** [comment]
Glad to hear that, crossing fingers so this is the latest RC!
