### ISSUE TITLE
RUP patcher is broken

### ISSUE THREAD

**Issue by Rainchus** [marcrobledo/RomPatcher.js#83]
When using a rup patch file, it fails to patch any data beyond the length of the original rom, and just fills it all with 00s. Everything inside the original rom's length is patched correctly though

**Comment by marcrobledo** [comment]
Can you link to a RUP patch that increases the the length of the original ROM?

**Comment by Rainchus** [comment]
Here's a patch for an english quest 64 z64 rom that produces said broken results 
[Quest64HMBeta.zip](https://github.com/user-attachments/files/17596241/Quest64HMBeta.zip)

**Comment by marcrobledo** [comment]
Fixed in commit df456bdfb9e331c4155e125f0539b9e3a2ee9006.
Overflow data wasn't being handled correctly. I also fixed RUP patch creation so it stores correctly the overflow data (if any).

Thank you! Make sure you are using version 3.1 (see the patcher site footer).

**Comment by Rainchus** [comment]
Just tried and it works. Thanks for the swift fix
